version: '3.4'

services:
  booksinformation:
    image: booksinformation:dev
    container_name: BooksInformation
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "BooksInformation"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - /Users/apple/Desktop/Ajmera Infotech/Source Code/BooksInformation/BooksInformation:/app
      - /Users/apple/Desktop/Ajmera Infotech/Source Code/BooksInformation:/src
      - /Users/apple/vsdbg/vs2017u5:/remote_debugger:rw
      - /Users/apple/.nuget/packages/:/root/.nuget/packages:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net6.0/BooksInformation.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true